### ISSUE TITLE
Add HTML5 History mode

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#100]
HTML History mode might be something to look into before launch as it removes the `#` in the middle of URLs. https://router.vuejs.org/guide/essentials/history-mode.html

_Originally posted by @spencerwahl in https://github.com/ramp4-pcar4/story-ramp/pull/94#pullrequestreview-849668096_

**Comment by yileifeng** [comment]
See [link](https://router.vuejs.org/guide/essentials/history-mode.html) for potential implementation details

**Comment by spencerwahl** [comment]
Just so its explicitly here: HTML History mode will require setup on the server side which is outlined in the link Yi Lei posted.

**Comment by dan-bowerman** [comment]
Good to know about the server side requirement. Thankfully, we do already use URL Rewrite in our IIS-deployed apps, and our future Azure apps too. I'm supportive of moving in this direction, if it removes the `/#/` from the URL as well as fixes our pagination issues too.

**Comment by dan-bowerman** [comment]
Dumb question: Will this still allow us to link directly to specific slides? The clients were pretty keen on that ability, which the ArcGIS.com solution doesn't provide.

**Comment by yileifeng** [comment]
I think this is independent from the functionality to directly link to slides, which was addressed in PR #101 and should be solved once merged.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/100?planning-poker) with ZenHub @RyanCoulsonCA @yileifeng @spencerwahl
