### ISSUE TITLE
Charts - Specify colours for data

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#103]
Not sure the best approach for this and am very open to ideas -- Importing a chart right now defaults to light blue, then orange if you add another row of data, then another colour, etc. If our charts only have one data row, they will always be blue. Is there a way we can specify a colour or an array of colours to force a different colour on a chart?

**Comment by yileifeng** [comment]
It can be configurable and passed as an array of colours, assuming it corresponds to the order of columns given in the csv file? If so, this would be a straightforward solution.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/103?planning-poker) with ZenHub @RyanCoulsonCA @yileifeng @spencerwahl
