### ISSUE TITLE
Page buttons jump around strangely 

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#106]
There are some strange issues with the second to last page button...

![Animation](https://user-images.githubusercontent.com/5294596/149675553-92665970-7216-441b-bff3-6bfc63669f6a.gif)

This issue is to assess and remediate so the expected page is transitioned to when selected.

**Comment by yileifeng** [comment]
Mentioned this in #102 but this is because these two slides have the same href tag name which results in this behavior so that will need to be investigated here.

**Comment by dan-bowerman** [comment]
Repeat slide names are definitely an occurrence in a couple of these products we're building, so there will be conflicts. I like the idea of prepending a number to the URL to resolve this!
