### ISSUE TITLE
DevOps Pipeline - swap environment variables

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#133]
Figure out a process to swap out environment variables (ArcGIS endpoints are probably the only one) at deployment time:

- dev: https://maps-cartes.dev.ec.gc.ca/arcgis
- qa: https://intranetqa.ncr.ec.gc.ca/arcgis
- prod: https://maps-cartes.ec.gc.ca/arcgis
- qc: https://section917.canadacentral.cloudapp.azure.com/arcgis

We've used Replace Tokens in the past, where you can set config variables (e.g. `{#arcgis#}` to beswapped with any of the environments above depending on which pipeline is used. However, this has problems when working locally... RAMP configs will fail when they try to load a service called `{#arcgis#}/rest/services/0000000/MapServer/1`. 

This is an active issue for CESI and CAM (both .NET solutions) as well, so it'd be great if the solution could work for those too.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/133?planning-poker) with ZenHub @RyanCoulsonCA @spencerwahl @yileifeng

**Comment by spencerwahl** [comment]
I think for CCCS we used two sets of config, one for local dev and another with the replaceable tokens.
