### ISSUE TITLE
Direct links only work when page is fully loaded

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#138]
A link such as http://localhost:8080/index-ca-en.html#/en/410b88da-0ed1-4749-903f-5e76c24e2e5f#3-in-situ-extraction does not jump to slide 3 as the anchor would assume, it just stays at the top. 
If you enter that link again in the same tab, only then it will jump you to the right spot. 

Can we resolve this? Would implementing some sort of delay help?

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/138?planning-poker) with ZenHub @RyanCoulsonCA @spencerwahl @yileifeng

**Comment by spencerwahl** [comment]
Alternative idea; change from using anchors to a query parameter so `?slide=3-in-situ-extraction` or something similar
