### ISSUE TITLE
Carousel arrows are missing in Canada.ca template

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#140]
The SVGs to show the left and right navigation arrows at the sides of the image carousel are not appearing on the Canada.ca page again. The arrows do appear on the basic index page. The RAMP SVGs are loading fine on both pages. 

![image](https://user-images.githubusercontent.com/5294596/151357476-d3d1a237-b143-4cd0-8546-60d41488c79c.png)
https://ecdc-webmappingappsstoryramp-asv.azurewebsites.net/index-ca-en.html#/en/410b88da-0ed1-4749-903f-5e76c24e2e5f#5-npri-substances-reported-for-oil-sands-mining-facilities

This task is to resolve and ensure that these SVGs don't vanish when loading in the Canada.ca template.

**Comment by spencerwahl** [comment]
This should be fixed after #146
