### ISSUE TITLE
Make chart panels fully responsive

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#154]
Ensure all panels and titles/headings are responsive when screen size changes, especially for chart panels. This mainly stems from the `:style="{ width: ${width}px }"` that is added for `slideshow-panel` and `chart-panel`. 

For charts, ensure that none of the chart content is cut-off in a mobile screen size. This can probably be done by adjusting the `highcharts-container`. Also for chart carousels, make sure the text content does not overlap with captions when vertically scrolling. 

Finally, if there are any suggestions to improve on user experience when transitioning between slides on mobile screens, please comment below and we can include that implementation with this issue.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/154?planning-poker) with ZenHub @RyanCoulsonCA @spencerwahl @yileifeng
