### ISSUE TITLE
Map legend open/closed state isn't being respected in mobile resolutions

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#162]
At the top of each RAMP config is a snippet that determines if the legend is open or not depending on screen size:
```
    "legend": {
      "allowImport": false,
      "isOpen": {
        "large": true,
        "medium": false,
        "small": false
      }
    }
```

The JSON above should only permit the legend above to be open by default if user is in a large resolution, but in small widths like a phone mobile, the legend is open anyways. Any way around this?

![image](https://user-images.githubusercontent.com/5294596/153855399-b324140b-4529-4a53-a64a-a5d1c988c3d0.png)

Worth noting the map title text is also cut off in this example.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/162?planning-poker) with ZenHub @RyanCoulsonCA @spencerwahl @yileifeng

**Comment by spencerwahl** [comment]
Things seem to be working properly when the map is loaded in mobile size after a refresh. Legend does not get closed on sizing down the window. We can possibly put a watch on the window and close the legend if it gets below a certain width, I am not sure if this is a use case to worry about (other than when demo-ing).

**Comment by dan-bowerman** [comment]
Thanks for checking further into it. I think we can close this out, the use-case of drastically changing window size mid-session is limited (perhaps just to me. :))
