### ISSUE TITLE
Enhance time slider on mobile

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#178]
Currently, maps with time sliders on mobile resolutions appear as follows: 

![image](https://user-images.githubusercontent.com/31557789/155202888-66d74a44-f952-408a-b209-3bb814032f87.png)

The main issues are that this covers up most of the data points and the labels are scrunched together. Find out if there is a good way around this, maybe adding a toggle to hide the time slider component could be an option.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/178?planning-poker) with ZenHub @RyanCoulsonCA @spencerwahl @yileifeng
