### ISSUE TITLE
Scrolling paginator on mobile + take full screen height

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#181]
If there are too many slides that overflow the mobile ToC, make the paginator scrollable just like the normal paginator behavior. Find and port this functionality over. In addition, I think it might make sense to have the mobile paginator take up the full screen height.  

![image](https://user-images.githubusercontent.com/31557789/155398109-c2424fd9-4143-4b61-a720-5e34dd6e8580.png)

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/181?planning-poker) with ZenHub @RyanCoulsonCA @spencerwahl @yileifeng
