### ISSUE TITLE
Backup/Source Control solution for clients of sandbox development folder

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#215]
This task is to implement an automated process that will 
a) allow the clients to run a script or executable that will automate a wholesale backup of the sandbox contents to this GitHub:
- project folders only!
- users should be able to run this simply and without command prompt access, e.g. double-click a file, click an accept box, done.

b) run the same function on a daily basis automatically - will likely need to be configured by WIG

**Comment by dan-bowerman** [comment]
Based on new revelations and discussions, we will probably want to use our internal TFS/DevOps for this process instead.

**Comment by spencerwahl** [comment]
Thoughts/plans:

b) is doable by running a small script (pseudo-code):
```
git add <project folder pattern>
git commit -am "regular backup"
```
Credentials should be managed outside the script for security reasons, for tfs this shouldn't be a problem anyways as far as I know.

WIG can then set up a `Schtasks` on Windows (which I believe our shared drives are on) or `cron`/`anacron` if they're on linux, to run the script once daily.
https://docs.microsoft.com/en-us/previous-versions/orphan-topics/ws.10/cc772785(v=ws.10)?redirectedfrom=MSDN

a) is more difficult, as far as I know you cannot execute a script on a remote computer just by running a file in a shared drive (for security reasons) I am unsure if you can execute the script on your own system, but if that is possible then we would have to add all editors to the tfs and not just the server's account.

**Comment by dan-bowerman** [comment]
This issue will become part of the Editor backlog in an upcoming phase, and will likely use an internal versioning system like TFS DevOps' Git.
