### ISSUE TITLE
[Oil Sands] Create markdown document based on existing French ArcGIS StoryMap content

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#22]
All of the images from the existing French Oil Sands StoryMap are available as asset files for use in the StoryRAMP Viewer. https://cartes.canada.ca/journal/content-fr.html?lang=fr&appid=6df630d9067240059ccc7cb33a68e188&appidalt=703d9327d99d445eb4c1e94a47c1933e

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/22?planning-poker) with ZenHub @JahidAhmed @RyanCoulsonCA @yileifeng

**Comment by JahidAhmed** [comment]
This is the initial draft up for the French markdown: [oilsands_fr.md](https://github.com/ramp4-pcar4/story-ramp/files/7547734/oilsands_fr.md)

I tried going through it for basic things like checking accents, formatting, etc. I'll check it once more when converting it to a config file (after the English configs are done)
