### ISSUE TITLE
Set-up OTS editors in Dev for analysis

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#220]
- [x] Highcharts editor
- [x] FGPA tool
- [x] Markdown editor?

**Comment by RyanCoulsonCA** [comment]
[This markdown editor](https://code-farmer-i.github.io/vue-markdown-editor/examples/base-editor.html) looks nice and seems pretty easy to set up. It has some accessibility issues on the demo page (not sure if that's an issue with the site), but maybe it's one we want to check out.

**Comment by dan-bowerman** [comment]
- Highcharts: https://environmental-maps.dev.ec.gc.ca/ramp-storylines/editor_highcharts/
- RAMP Editor/FGPA: https://environmental-maps.dev.ec.gc.ca/ramp-storylines/editor_ramp/samples/fgpv-author.html
- Markdown Editor: TBD (See #230)
