### ISSUE TITLE
Focus issues are blocking links from being followed

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#268]
From @roryhofland: 

1. After focusing on a RAMP map instance, clicking on an internal page link doesn't navigate to the section, even though the URL is updated.
2. Firefox on Windows
3. Click/focus on a RAMP instance, then try to navigate to another section via hyperlinked text

**Comment by yileifeng** [comment]
One fix for this issue as well as likely #276 would be to remove `rv-trap-focus` on the map instances. However, unsure about potential drawbacks this could create as I am not the most familiar with RAMP3 focus manager. Doing some keyboard nav testing shows everything appearing to work just fine. If anyone has alternative solutions or knows the use case of this property, feel free to comment.

**Comment by RyanCoulsonCA** [comment]
The purpose of having `rv-trap-focus` on the instance is basically to keep focus within the RAMP app once it's been focused on (once you've tabbed through everything in the app, focus will loop back to the first button in it). See an example below:

![Animation](https://user-images.githubusercontent.com/25874602/201930998-4bb24e4f-b276-464e-9a4f-77536549bf96.gif)


And here's an example of navigating the app with `rv-trap-focus` removed. Notice that the focus goes out of the app once you've navigated through the buttons:
![Animation](https://user-images.githubusercontent.com/25874602/201930348-0588abbe-1d45-4d10-a5ef-00ee6fd0129c.gif)

**Comment by dan-bowerman** [comment]
Let's remove `rv-trap-focus` and see what happens. We need people to be able to break out of the map and select links external to the map.
