### ISSUE TITLE
Distinguish between links that will change the panel vs. open a new tab

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#304]
It would be nice to know if a link within a Storylines product is going to open an image/map/chart in the right-hand panel vs. open up a new tab. Different CSS, an icon (![Image](https://user-images.githubusercontent.com/5294596/207090519-1e2dae5b-178c-4995-90d6-5304298dd458.png)), additional text, I am open to ideas or suggestions.

**Comment by RyanCoulsonCA** [comment]
This is technically already a feature, but it's not super clear. Links that change the panel have a dotted underline while links that open a new tab have a solid one. We can definitely add something else in if we want to make it more obvious.

Link that changes the panel:
![image](https://user-images.githubusercontent.com/25874602/207092300-4f907217-98ec-4f2a-b1ef-eecae948f722.png)

Link that opens a new tab:
![image](https://user-images.githubusercontent.com/25874602/207092435-4dd528e4-977b-437e-b1ed-c6c19817d905.png)

**Comment by spencerwahl** [comment]
I think the most clear way to differentiate is the icon Dan included in his comment. This *should* be doable by just changing the CSS for external links to add the icon to the `::after` pseudo-element.
