### ISSUE TITLE
Enable choosing between RAMP3 and RAMP4

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#312]
The configuration for a Storylines product could specify which version of RAMP to use, as we will most certainly be maintaining both types for the next year or so. This would prevent the need to migrate all older configuration files to RAMP4, and make it easy for new products to adopt RAMP4 straight out of the gate.

**Comment by james-rae** [comment]
Adding a thing that might not be obvious & require an extra bit of code (depending on how things work in the land of the RESPECT editor).

RAMP2 has the `initialFilteredQuery` layer config property, which I know is being used in a few ramphlet maps to only display a subset of a layer.  While this property "works", it's not the best. When opening the grid, the entire layer's attributes get downloaded and then filtered client side. It might also be possible that if clicking the symbol toggles, it will erase the initial filter (this might have gotten patched? I'm old and can't remember).

RAMP4 supports that config property, but introduces a new property `permanentFilteredQuery`. This will solve the above problems and is overall better for any scenario where you plan to keep the filter in place for the entire lifetime of the layer. Note this is not on the `v4.0.0` version, but is on the current `main` build.

The RAMP4 "config converter" will map `initial` to `initial` when parsing an R2 config. If this version picker wants to map `initial` to `permanent`, will need an `if` or two.

**Comment by dan-bowerman** [comment]
I think given migration priorities, that we won't need to worry about this one. 

Will discuss during our meeting and close this one if we're all in agreement.
