### ISSUE TITLE
On-demand loading

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#313]
I don't know if it is possible to do something about this, but I wanted to record it for discussion: 

The preferred method of downloading, done automatically in Chrome and Firefox, is to scroll through the Storylines product and resources will download as they are accessed. However, in MS Edge, if you load the Storylines product and stay at the top, everything gets downloaded immediately, which both causes the scrolled page to jump around a bit as images and maps load, and is a tax on bandwidth (Priority Places is almost 35MB when downloaded all-at-once). Is there any way we can make Edge act more like FF and Chrome, downloading only the assets that are in view or scrolled past?

**Comment by james-rae** [comment]
My cursory searches of the codebases make it look like a few of these tricks (lazy load in particular) could be applied. Should help with the image parts

https://www.builder.io/blog/fast-images

**Comment by dan-bowerman** [comment]
Duplicate #315
