### ISSUE TITLE
Full screen challenges

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#335]
Using the "full screen" command in RAMP-based maps can cause the wrong map to open. Detailed reports here:

Found by: Olivieri,Celina (elle, la | she, her)
1. Product: Academic Challenge: [NPRI Academic Challenge - Canada.ca (ec.gc.ca)](https://environmental-maps.dev.ec.gc.ca/ramp-storylines/index-ca-en.html#/en/0plctqat-zpde-a8ad-hji3-f6wkf476jb6t)
2. Language: Both
3. Issue Description: Expanding the Academic Challenge map shows incorrect map.
4. Steps to Reproduce: 
a.	Scroll to 'University of Sherbrooke' chapter
b.	Click Academic Challenge hexagon 
c.	Click hamburger menu then Full Screen
d.	Expected: I expect the screen to expand to show the Academic Facilities. 
e.	Actual: The interactive menu shows the Universrity of Sherbrooke options

Found by: Kugathas,Tissan
1. Product: NPRI Data integration - Climate Change - Canada.ca
2. Language: English
3. Issue Description: Map highlighting the location of facilities and their sector that have reported to the GHGRP is showing a map with different layers when in full screen. The layers that are showing are layers that are on the other maps on the storyline.
4. Steps to Reproduce (if relevant): Edge. Scroll down to the to the map highlighting the location of facilities. Enter full screen view. Expected to see a full screen view of the map with Facilities' locations and their sector. Actual result shows the distribution of Facilities layer.

Found by: Nashed,Daniel
1. Product: Substance Overview: Aluminum https://environmental-maps.dev.ec.gc.ca/ramp-storylines/index-ca-en.html#/en/887dadc1-7936-4628-9c27-79da8da891ea 
2. Language: Both
3. Issue Description: The animation slider (goes from 2008-2021) disappears for some maps once they are made full screen. Once this happens, all other sliders for the maps that have one disappear once they are put full screen as well.
4. Steps to Reproduce (if relevant): Microsoft Edge, Chrome (Haven't tested other browsers yet). Make the specified map full screen, the slider will disappear. Now if you try to make any other maps that have a slider full screened the slider will disappear as well. Can reproduce this issue consistently by making the last map "Disposals and Off-Site Transfers by Aluminum Production Facilities 2008 to 2017" full screen first.

**Comment by spencerwahl** [comment]
Issue was a combo of z-index conflicts and a hidden bug in RAMP2 code (that doesn't cause problems in normal circumstances). I fixed the issue on the storylines side and submitted an issue to the RAMP2 repo to track the hidden bug in case this comes up somewhere else.
