### ISSUE TITLE
Long text/markdown contents in right panel is opening at the center of contents instead of top

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#349]
The dashboard in full desktop resolution is quite long, and is opening up in the "middle" of the content. See the screenshots below. The first screenshot is what immediately appears on the right when clicking the highlighted link. The second screenshot is scrolling up to the top of the dashboard content, which is also the top of the left panel content. 

(Example, requires VPN, and this link won't last forever: https://environmental-maps.dev.ec.gc.ca/cws_ramp-storylines_sandbox/index-ca-en.html#/en/priority-species_especes-prioritaires#5-barren-ground-caribou, Barren-ground Caribou slide, "Please refer to our barren-ground caribou dashboard" link)

![image](https://github.com/ramp4-pcar4/story-ramp/assets/5294596/b1dd113b-3cc2-47de-b968-118d020b2058)

![image](https://github.com/ramp4-pcar4/story-ramp/assets/5294596/a952d732-f0e2-4329-b534-efcfde529583)

**Comment by spencerwahl** [comment]
Plan is to scroll to the top of the "right" dynamic panel on it changing, should hopefully handle desktop and mobile confusions.
