### ISSUE TITLE
Upgrade Vue CLI to Vite

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#381]
Recommended build toolchain for Vue 3 projects. Might be worthwhile considering a significant improvement in development server speed. Can be done alongside the Vue 3 refactor.

**Comment by AleksueiR** [comment]
Who recommends it?

**Comment by yileifeng** [comment]
Mentioned as part of the official migration [docs](https://v3-migration.vuejs.org/recommendations.html), much faster startup times for performance.

**Comment by AleksueiR** [comment]
Is it built by the same guys who built Vue? Seems like of a lot of official tooling is being deprecated in favour of some new ones. Strange how they suggest you switch to a different tool instead of release a new version of the old one that is better geared to Vue 3.

**Comment by yileifeng** [comment]
Looks like the same Vue team: https://vitejs.dev/team.html
