### ISSUE TITLE
Option for centered content

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#403]
The TCEI StoryMap project (https://storymaps.arcgis.com/stories/a4e825956b4a402ebe13dbceeba66321, reach out for credentials) demonstrates this well. 
![image](https://github.com/ramp4-pcar4/story-ramp/assets/5294596/d5ad06cc-1203-4a75-98ba-9a8a432e5bcb)

A number of StoryMap products have a layout that is more centered than left or right aligned. I have seen this in one or two panel situations. 
Should this be a setting applied globally to the entire Storylines product? Or per slide? 

Follow-up work to R.E.S.P.E.C.T. will need to be spun off from this once implemented.

**Comment by RyanCoulsonCA** [comment]
Panel content can be be centered using the `customStyles` attribute:

```
{
   ...
   "panel": [
      {
         "title": "Panel",
         "content": "..."
         "type": "text",
         "customStyles": "text-align: center;"
      }
   ]
   ...
}
```

Example:


![Image](https://github.com/ramp4-pcar4/story-ramp/assets/25874602/5df721c8-a09d-4fc6-8ac1-638957d9838b)
