### ISSUE TITLE
Create map panels

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#42]
Implement the map panel component `map-panel.vue` that creates a RAMP map instance given a simplified RAMP2 config.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/42?planning-poker) with ZenHub @JahidAhmed @RyanCoulsonCA @yileifeng
