### ISSUE TITLE
Mobile: When Chapter Title is very long and has a map and text, user can only read one line of text at a time

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#424]
_Found through Storylines QA review by @celinaolivieri_ 

## Description
Long titles for maps are taking up a large amount of screen real estate in mobile layouts. 

## Environment

Mobile

## Screenshots
![image](https://github.com/ramp4-pcar4/story-ramp/assets/5294596/e8a4dc28-1487-464b-a47e-a25e8d3d82ea)

## Steps to reproduce

1. On mobile open either storyline.
2. Scroll to a chapter with a long title with both a map and text.

## Expected behavior

I expect to be able to read the text easily.

## Actual behavior
Because the title is so large and the map is big, I can only look at a few lines of the text at a time

Note: screenshot to the right

Note: Raising this for future consideration!

**Comment by yileifeng** [comment]
Raising the prio on this one after looking at how TCEI product looks: 

![image](https://github.com/user-attachments/assets/fe200018-17d9-490e-b891-391898501900)

**Comment by RyanCoulsonCA** [comment]
Doesn't look like this will be fixed by my existing PR. Shouldn't be as much work to fix after that one is merged in, though.

**Comment by RyanCoulsonCA** [comment]
This should now be fixed after https://github.com/ramp4-pcar4/story-ramp/pull/505 is merged
