### ISSUE TITLE
Integrate with R4MP npm package

### ISSUE THREAD

**Issue by szczz** [ramp4-pcar4/story-ramp#431]
## Description

Discovered by @RyanCoulsonCA  

Currently the RESPECT editor needs the R4MP files in the public folder to display maps, however this isn't ideal as 
The attempt to access window.RAMP.createInstance() is coming from within the storylines project.

Look into integrating the R4MP npm package in the storylines project.

**Comment by mohsin-r** [comment]
Would also like to cross-link #415 here as it is somewhat related.
