### ISSUE TITLE
Basemap logos are not displaying

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#434]
## Description

The "logos" for the basemaps are not displaying in the basemap selector, in the context of the Storylines Editor. 

## Environment

May only be an issue when Storylines is integrated with .NET/Express components

## Screenshots

![image](https://github.com/ramp4-pcar4/story-ramp/assets/5294596/99dc28eb-1db9-4671-9036-007011f6768d)

## Steps to reproduce
1. Create a map in Storylines, open the config-editor
2. Select the basemap selector in any embedded map instance, e.g. setting map extents

## Expected behavior
I expect to see the basemap thumbnail images

## Actual behavior

I see the "stub" clipart instead. 

## Possible solution
Encode these thumbnails directly?

## Related issues

#432?

**Comment by szczz** [comment]
Config editor needs to correctly default the paths to the basemap logos. @mohsin-r
