### ISSUE TITLE
Update to the latest version of CDTS

### ISSUE THREAD

**Issue by szczz** [ramp4-pcar4/story-ramp#469]
## Description

The performance testing team is experiencing errors when load testing a couple of our storylines products. They've reported a recurring error coming from https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/compiled/soyutils.js

This file doesn't seem to contain anything. This is whats returned when accessing it from the browser.

![image](https://github.com/user-attachments/assets/727b63fb-4a24-4c70-a87e-dca3c683b0ad)

We're hoping that an update to the latest version of CDTS might remove reference to this file and resolve the errors the performance testing team are experiencing.

**Comment by dan-bowerman** [comment]
CDTS repo: https://github.com/wet-boew/cdts-sgdc
