### ISSUE TITLE
Ensure consistent padding following a full slide map panel

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#487]
## Description

For the TCEI product following a full slide map panel, there is not enough padding between the map slide and the following slide. Keep the stacked padding consistent between all slides. 

## Screenshots

![image](https://github.com/user-attachments/assets/f6e6b968-ef32-441a-a56b-44f7235e563e)

## Steps to reproduce

Navigate to the TCEI teleported map or any other full slide map and notice the reduced padding with the next slide.

## Possible solution

There is a `top-8` and `top-16` Tailwind class applied to multimedia panels. Check if these can be removed which might solve the issue. @RyanCoulsonCA said these used to prevent the content from being hidden by the product header so ensure this does not become an issue. If all else fails, we can just add custom padding to particular slides in the TCEI product.

**Comment by RyanCoulsonCA** [comment]
Will be fixed when #448 is merged.
