### ISSUE TITLE
Create introduction slide

### ISSUE THREAD

**Issue by RyanCoulsonCA** [ramp4-pcar4/story-ramp#49]
Create the large introductory slide component, which contains a logo, title, and subtitle.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/49?planning-poker) with ZenHub @JahidAhmed @RyanCoulsonCA @yileifeng
