### ISSUE TITLE
Investigate Excel to Highcharts workflow

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#65]
Users are primarily going to provide data in Excel. Investigate methods, strategies, pros and cons for options to quickly convert Excel to Highcharts config format. 

Things to consider:

- Should be easy for users to potentially use/configure
- If an option's process is not already easy, can we make it easy?
- Users generally can't install software (but there may be leeway for Excel plugins etc)
- Dependencies available in the Software Center are fair game (e.g. Python)

Some example data attached: 

- [Ethlyene glycol release trends, by sector 2010-2019 (tonnes).xlsx](https://github.com/ramp4-pcar4/story-ramp/files/7634073/Ethlyene.glycol.release.trends.by.sector.2010-2019.tonnes.xlsx)
- [Breakdown of facilities reporting ethylene glycol to the NPRI for 2019.xlsx](https://github.com/ramp4-pcar4/story-ramp/files/7634075/Breakdown.of.facilities.reporting.ethylene.glycol.to.the.NPRI.for.2019.xlsx)
- [Ethlyene glycol disposal and recycling trends, by sector 2010-2019 (tonnes).xlsx](https://github.com/ramp4-pcar4/story-ramp/files/7634076/Ethlyene.glycol.disposal.and.recycling.trends.by.sector.2010-2019.tonnes.xlsx)

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/65?planning-poker) with ZenHub @JahidAhmed @RyanCoulsonCA @yileifeng

**Comment by yileifeng** [comment]
Some notes for reference: 

**Option 1 - Convert to CSV file**
- Least amount of work overall - save `.xlsv` file as `.csv` and utilize the highcharts `data` module and the `csvURL` parameter which takes a CSV data path (either hosted on web or local file)
- If it is a web service with dynamic data there is an option to keep chart up to date with `enablePolling: true` 
- Default format: first row interpreted as series names, first column interpreted as category names (current sample files are of this format) - there are additional formatting options I haven't had a chance to test out yet 
- Problem: how to specify different graph configurable options/types, potential incorrect file formatting, etc. 

**Option 2 - Convert to Google Spreadsheet**
- Similar to first option also utilizing the highcharts `data` module but requires two parameters `googleAPIKey` and `googleSpreadsheetKey`
    - `googleSpreadsheetKey` is contained in URL (e.g. "https://docs.google.com/spreadsheets/d/*spreadsheetID*/edit#gid=...")
    - `googleAPIKey` obtained via "developers.google" and needed for authentication purposes  
- Good for allowing other team members to edit or keep up-to-date on chart data

**Option 3 - Convert to CSV file and have developers parse data with config options**
- Same as first option but additional coding work to parse CSV file for data (but this can also be optional if files will be correctly formatted) to solve potential inconsistent formatting
- Main difference is that we include more chart configurable options as part of the StoryRamp schema for `chartPanel`, for instance properties such as `chartType`, `color`, `subtitle/caption`, `labels`, etc and then pass those as options when initializing chart
- This approach makes the most sense to me so far for implementation

**Option 4 - User manually converts data into highcharts config structure JSON file**
- Fairly inefficient and time consuming (having to extract data from already formatted file)
- Requires users to have a basic understanding of highcharts API documentation
- Most customizable option for users 

Open to all other ideas here. 

We can also have a hybrid approach where we accept multiple input types and user can also pass in a formatted highcharts config json file as input if they want.
