### ISSUE TITLE
[Oil Sands] Make the last slide's left panel take up the entire width

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#8]
Currently the last panel is squished into the left pane, with nothing on the right. Span the left slide to take up the entire width of the StoryRAMP.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/8?planning-poker) with ZenHub @JahidAhmed @RyanCoulsonCA @yileifeng

**Comment by yileifeng** [comment]
This is done as part of the new config structure
