### ISSUE TITLE
Canada.ca template: Make the view frame wider

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#81]
The original StoryRAMP product (though using an iframe) has a much wider view for its StoryMap: https://maps.canada.ca/journal/content-en.html?lang=en&appid=703d9327d99d445eb4c1e94a47c1933e&appidalt=6df630d9067240059ccc7cb33a68e188. 
This approach was apparently approved by Comms at some point, so if possible, let's maximize the width in our Canada.ca template.

**Comment by RyanCoulsonCA** [comment]
This should be done once https://github.com/ramp4-pcar4/story-ramp/pull/74 is closed.

Preview from the PR, things can be changed if needed:
![image](https://user-images.githubusercontent.com/25874602/147780362-1fe0b7ec-8162-48c2-a3f1-e7d86d9990f2.png)

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/81?planning-poker) with ZenHub @spencerwahl @yileifeng @RyanCoulsonCA
