### ISSUE TITLE
Add highcharts configurable options to StoryRamp config

### ISSUE THREAD

**Issue by yileifeng** [ramp4-pcar4/story-ramp#85]
Resulted from #65, it was discussed that we should have the option of customizing high charts output through StoryRamp config options. These can then be passed into `chartOptions` when processed in `chart-panel.vue`. 

Some basic properties to include from an initial glance: 
- titles, subtitles, captions, axis titles
- chart type
- graph color 
- credits (boolean)
- additional labels
- padding/border? 
- export options?

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/85?planning-poker) with ZenHub @spencerwahl @yileifeng @RyanCoulsonCA
