### ISSUE TITLE
Name this application!

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/story-ramp#88]
We need a name for StoryRAMP products that isn't "StoryRAMP", for the following reasons:

1. It's too close to StoryMap (an ArcGIS product from Esri)
2. It's not bilingual and wouldn't translate well (Best I can come up with is "PCAR L'Histoire" which rhymes but still doesn't make sense).

Considerations:
- It should go into the URL e.g. enviromental-maps.canada.ca/storyramp-histoirepcar
- It might need to go on a logo 
- It will be referenced in countless documents, APM, etc. 
- We should keep RAMP (PCAR) in the name, if possible.

**Comment by james-rae** [comment]
![RampTales](https://user-images.githubusercontent.com/7585245/148247858-5a91a845-aa34-4302-b234-717bc4c9b030.png)

**Comment by dan-bowerman** [comment]
I forgot about RAMPTales, it actually translates more or less the same, but we'll need to decide if we'd rather be sued by Esri or Disney.

**Comment by james-rae** [comment]
No clever names comes to mind. Some boring suggestions.

- RAMP Journeys
- RAMP Tour
- RAMP Guidebook
- RAMP Brochure
- RAMP Pamphlet ( RAMPhlet ✔️ )
- RAMP 'Zine
- RAMP Extra! (newspaper term)

Less boring that won't get approved

- Scrolly RAMP
- RAMP 'n' Scroll
- RAMPers Digest
- Rampy McRampface (credit to Mr. Wahl)
- Tour de RAMP

**Comment by spencerwahl** [comment]
More boring suggestions:

RAMP folio
RAMP book

folio and tour might be able to stay as folio and tour in translation.. if thats a bonus

**Comment by milespetrov** [comment]
Tales from the RAMP
RAMP It Up
RAMP Plot
RAMP Diegesis
RAMP StoryLine
RAMP Stamp

**Comment by RyanCoulsonCA** [comment]
Random ideas:

- RAMP Notes
- RAMP Slides
- RAMP Sheets
- RAMP Pages
- RAMP Chapters

**Comment by james-rae** [comment]
If we choose RAMP Book I have an icon for us.

![rampbook](https://user-images.githubusercontent.com/7585245/148420708-b69c62fd-7542-4e41-9987-89fd163a2fec.png)

**Comment by yileifeng** [comment]
Few other ideas that came to mind: 
- RAMP Quest
- RAMP Chronicle 
- RAMP Album
- Art of RAMP
- RAMP Journal
- Scenes from RAMP

From the existing suggestions, I quite like RAMP Folio, RAMP Book, RAMP Stamp, and Tour de RAMP.

**Comment by dan-bowerman** [comment]
'RAMP Gazetteer' for the throwback.

Shortlist from the suggestions above (thanks everyone!), we will discuss in a future meeting:

- RAMP Pamphlet ( RAMPhlet ✔️ )
- RAMP Pages
- RAMPfolio 
- RAMP Album (or some variation)
- RAMP StoryLine
- RAMP Journals
- Tour de RAMP (I know you were being funny with this but that's actually pretty good)
