### ISSUE TITLE
Determine a way to display slides with multiple panels on mobile resolutions

### ISSUE THREAD

**Issue by RyanCoulsonCA** [ramp4-pcar4/story-ramp#97]
Currently, trying to view a slide on a StoryRAMP page on a mobile resolution doesn't look very nice. Horizontal scrolling is required to see all of the text and to see the right panel most of the time. We should come up with a better way to display slides that have two panels when using a mobile resolution.

A couple of options:
- Add a labelled button (`show second panel` or something else) that displays the second panel over top of the first panel when clicked.
- Display the second panel on a row of its own below the first panel. We may need some way of showing that it's connected to the first panel.
- Possibly a solution similar to the slideshow panel where we add left and right arrows to switch back and forth between the first and second panel.

Any other ideas?

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/97?planning-poker) with ZenHub @RyanCoulsonCA @yileifeng @spencerwahl

**Comment by dan-bowerman** [comment]
We might want to up the estimate on this one (previous was 5).

Original StoryRAMP demo: https://storyramp.z27.web.core.windows.net/

Aleks' mockups for new solution: https://www.figma.com/file/qo63Pj8XyVRYPn5k3vWOyw/RAMP?node-id=50%3A6 

I think we are going with the "Alternate Option" from the link above. This will require us to:

- [ ] Add back in the lost functionality where long text continues to scroll in a slide while the map/graphic stays consistent
- [ ] Display the multimedia asset at the top of the screen (image, chart, carousel, map) with an option to full screen (?)
- [ ] The text flows underneath the multimedia, other slides are hidden until scrolled to
- [ ] what else??

**Comment by yileifeng** [comment]
Adding `class="sticky self-start top-16"` to graphic panels should restore the scrolling text behavior.

**Comment by yileifeng** [comment]
Can we confirm a final decision on which option to go with for implementation? After reviewing the options, I like the original preferred option since it appears to be more consistent with current behavior and the amount of work should be relatively similar I think.

**Comment by dan-bowerman** [comment]
Yes, let's go with the preferred option then. Aleks will be pleased.
