### ISSUE TITLE
Anchor tag in URL to jump to specific slide is not working

### ISSUE THREAD

**Issue by RyanCoulsonCA** [ramp4-pcar4/story-ramp#98]
It looks like after we added the ability to load the config file through the URL we can no longer link to a specific slide.

For example when running locally, http://localhost:8080/#oil-sands-deposits should jump to the slide titled Oil Sands Deposits. It now goes to the Canada 404 page instead.

This issue is likely caused due to us switching over to Vue Router. Spencer mentioned the history mode setting in [this PR review](https://github.com/ramp4-pcar4/story-ramp/pull/94#pullrequestreview-849668096) which may be useful in solving this issue, but I'm not 100% sure.

**Comment by dan-bowerman** [comment]
It tries to go to the right place if you visit http://localhost:8080/en/00000000-0000-0000-0000-000000000000#oil-sands-deposits, but then redirects to the 404 page anyways.
