### ISSUE TITLE
Make dynamic panel change noticeable on mobile resolution

### ISSUE THREAD

**Issue by RyanCoulsonCA** [ramp4-pcar4/story-ramp#99]
Blocked by #97 

When the user clicks on a link on a dynamic slide that changes the right panel, it should show them this right panel on mobile resolutions. How we do this will depend on how we choose to implement #97.

**Comment by dan-bowerman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/StoryRAMP-61810f925832ab001db602b8/issues/ramp4-pcar4/story-ramp/99?planning-poker) with ZenHub @RyanCoulsonCA @yileifeng @spencerwahl
